"use client"
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "sonner";
import { usePathname } from "next/navigation";
import { CartContext } from "./_context/CartContext";
import { useState } from "react";

const outfit = Outfit({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params = usePathname()
  const showHeader = params == "/sign-in" || params == "/create-account" ? false : true

const [updateCart , setUpdateCart]= useState(false)

  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} antialiased`}
      >
        <CartContext.Provider value={{updateCart, setUpdateCart}}>
          {showHeader && <Header />}
          {children}
          <Toaster />

        </CartContext.Provider>

      </body>
    </html>
  );
}
